name: Linux / C++ - Valgrind

on:
  push:
    branches:
      - master
      - 'releases/**'
      - overhaul
  pull_request:
    branches:
      - master
      - overhaul

jobs:
  build:
    container:
      image: jackgerrits/vowpalwabbit-ubuntu-2004
    runs-on: ubuntu-latest
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
      - name: Install Valgrind
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y valgrind
      - name: Build C++ VW binary
        shell: bash
        run: ./.scripts/linux/build-minimal.sh Release
      - name: Run test suite with Valgrind
        shell: bash
        run: ./.scripts/linux/test-valgrind.sh
      - name: Run unit tests with Valgrind
        shell: bash
        run: ./.scripts/linux/unit-tests-valgrind.sh
