name: Check code formatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_code_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check code formatting
        shell: bash
        run: sudo apt install clang-format
      - name: Check code formatting
        shell: bash
        run: clang-format-diff --help
      - name: Check code formatting
        shell: bash
        run: ./utl/clang-format check
        env:
          GH_WORKFLOW_LOGGING: true
          WARNING_AS_ERROR: true