name: Check code formatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_code_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install clang-format
        shell: bash
        run: sudo apt install clang-format
      - name: Check code formatting for diff
        shell: bash
        run: |
          git diff origin/master HEAD -U0 --no-color | clang-format-diff -r '^.*\.(cc|h)$' -p1 > clang_format_diff.txt
          if [ -s clang_format_diff.txt ]; then
            cat clang_format_diff.txt
            echo "::error:: Formatting issues found"
          fi